"""Text strings."""

ELLIPSIS = ' ...'
ACCEPT = 'Accept'
DELETE_PROMPT = 'Are you sure you wish to delete this record?'
CLOSE = 'Close'
DELETE = 'Delete'
EDIT = 'Edit'
VERIFY = 'Verify',
EXIT = 'Exit'
HIDE = 'Hide'
NEW = 'New'
NO_SUCH_FILE = 'no such file or directory'
OK = 'OK'
OPEN = 'Open'
CONFIG = 'Settings'
QUIT = 'Quit'
SAVE = 'Save'
SELECT = 'Select'
SHOW = 'Show'
DIRECTORS = 'Director\'s'
PLAYERS = 'Player\'s'

REBATE_REPORT = 'att_report'
REBATE_FILE_PREFIX = 'att_rebate'
F2F = 'f2f'
BBO = 'bbo'
CF_PREFIX = 'cf'
CSV = 'csv'
MEMBERSHIP = 'membership'
EMAIL = 'email'
RESET = 'reset'
TITLE = 'Players\' Attendance Rebates'
CLUB = 'CLUB'
